### ISSUE TITLE
Failed to build toolchain-llvm using Makefile

### ISSUE THREAD

**Issue by kaitoukito** [pulp-platform/ara#85]
I failed to build toolchain-llvm on MacOS.
There are several similar errors, and the first FAILED log is as follows:
<img width="1920" alt="截屏2021-11-08 下午4 57 55" src="https://user-images.githubusercontent.com/34410167/140712869-667b76b0-6af1-4f2f-9800-f269360c85bc.png">
I'm not sure if these warning logs previous to the FAILED logs will be helpful for debugging.
<img width="1920" alt="截屏2021-11-08 下午5 05 58" src="https://user-images.githubusercontent.com/34410167/140713918-e8c4ca2a-3ffc-42a3-a4f8-c6f42c608fc0.png">
<img width="1920" alt="截屏2021-11-08 下午5 07 05" src="https://user-images.githubusercontent.com/34410167/140714077-147eeb51-1e87-4001-89e7-900cf2e66c5a.png">

**Comment by mp-17** [comment]
Hello @kaitoukito,

We never tried to install the toolchain on MacOS, but we will try. 
I guess the problem here occurs when executing the `toolchain-llvm-rt` Makefile target. Is this right? So, `LLVM` and `newlib` are installed correctly.
Anyway, it would be nice to enable a `verbose` compilation to have more details about what went wrong.

Best regards,
Matteo

**Comment by kaitoukito** [comment]
Thanks, I will try it on Linux through VirtualBox :)
